name: TEST AMP Retry
description: |
  TEST AMP Retry.

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-10-02"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: start_application
    name: CML Llama2 Chatbot Interface
    subdomain: cml-llama2-ui
    script: simple-api-application.py
    short_summary: Create and start CML Llama2 frontend application
    long_summary: Create and start CML Llama2 frontend application. Ensure available GPUs for best performance. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 16
    gpu: 1
    environment_variables:
      TASK_TYPE: START_APPLICATION
